name: Publish Docker image
on:
  release:
    types: [published]

jobs:

  test:
    name: Test nodejs app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.hub.docker.com
          repository: roscloud/ros-statuspage-api
          tags: latest
      